openapi: 3.0.3
info:
  title: Books
  description: "Fetch books by book's title, author, or isbn"
  version: "v2"
servers:
  - url: http://localhost:8041/api
    description: local

paths:
  /v2/books/search:
    get:
      summary: "v2 latest version - Fetch books by book's title, author, or isbn"
      parameters:
        - in: query
          name: searchType
          description: "The search type we want to search by (title, author, or isbn)"
          required: true
          schema:
            type: string
            enum:
              - title
              - author
              - isbn
            example: title
        - in: query
          name: searchValue
          description: "The search value we want to search for (Throne of glass, Sarah\
          \ J. Maas, or isbn_9788377478844)"
          required: true
          schema:
            type: string
            example: Throne of glass
        - in: query
          name: page
          description: Page of the results
          required: false
          schema:
            type: integer
            example: 2
        - in: query
          name: limit
          description: Limit the results
          required: false
          schema:
            type: integer
            example: 25
      responses:
        "400":
          description: Missing required arguments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "500":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "200":
          description: A list of found books
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    minItems: 0
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        externalId:
                          type: string
                        title:
                          type: string
                        firstPublishYear:
                          type: integer
                        authors:
                          type: array
                          items:
                            type: object
                            properties:
                              schema:
                                $ref: "#/components/schemas/Authors"
                        isbns:
                          minItems: 0
                          type: array
                          items:
                            type: array
                            description: A list of book's ISBNs
  /v1/knygos/paieska:
    get:
      summary: "v1 lithuanian endpoint - Fetch books by book's title, author, or isbn"
      parameters:
        - in: query
          name: paieskosTipas
          description: "The search type we want to search by (title, author, or isbn)"
          required: true
          schema:
            type: string
            enum:
              - title
              - author
              - isbn
            example: title
        - in: query
          name: paieska
          description: "The search value we want to search for (Throne of glass, Sarah\
          \ J. Maas, or isbn_9788377478844)"
          required: true
          schema:
            type: string
            example: Throne of glass
        - in: query
          name: puslapis
          description: Page of the results
          required: false
          schema:
            type: integer
            example: 2
        - in: query
          name: limitas
          description: Limit the results
          required: false
          schema:
            type: integer
            example: 25
      responses:
        "400":
          description: Missing required arguments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "500":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        "200":
          description: A list of found books
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    minItems: 0
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        externalId:
                          type: string
                        title:
                          type: string
                        firstPublishYear:
                          type: integer
                        authors:
                          type: array
                          items:
                            type: object
                            properties:
                              schema:
                                $ref: "#/components/schemas/Authors"
                        isbns:
                          minItems: 0
                          type: array
                          items:
                            type: array
                            description: A list of book's ISBNs
components:
  schemas:
    Errors:
      properties:
        error:
          type: integer
          description: Status code
        message:
          type: string
          description: Exception message
    Authors:
      properties:
        id:
          type: integer
        name:
          type: string